---
name: OpenCloud Image Management
author: Didi Hoffmann <didi@green-coding.io>
description: "
- Create a new space incl. description
- Upload 10 images
- Preview (preview service) of the images
- Implicit: Search Indexing with Tika
- Delete all files - Empty the recycle bin"
ignore-unsupported-compose: true

compose-file: !include docker-compose.yml

services:
  gcb-playwright:
    image: greencoding/gcb_playwright:v19
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
       DISPLAY: ":0"
    networks:
      opencloud-net:
    setup-commands: # moving repo so we can create files there (is read only)
      - command: cp -r /tmp/repo /tmp/repo-copy
      - command: cd /tmp/repo-copy/downloads && make
        shell: bash

  opencloud:
    setup-commands:
      - command: sleep 10
  collabora:
    setup-commands:
      - command: sleep 10
  traefik:
    setup-commands:
      - command: sleep 10

flow:
  - name: Images
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/playwright/images.py
